# Generated by Django 5.1.7 on 2025-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_account_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(default="banunani021@gmail.com", max_length=254),
        ),
    ]
